//! JSON Schema generation from the canonical Rust model (written to `core/schemas/`).
//!
//! Schemas are generated, never edited by hand: `kb schema --write` regenerates them and
//! `kb schema --check` (plus the `schema_conformance` test) fails on drift. Constraints
//! that JSON Schema can express are declared with `#[schemars(...)]` attributes on the
//! model; runtime-only rules are listed in `core/schemas/README.md`. The CLI envelope
//! schema is assembled here from the protocol constants, [`ErrorCode::ALL`] and the clap
//! command definitions.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use clap::CommandFactory;
use schemars::JsonSchema;
use schemars::generate::SchemaSettings;
use serde_json::{Map, Value, json};

use crate::cli::args::Cli;
use crate::error::{ErrorCode, KbError, Result};
use crate::model::registry::{ConceptsFile, FeaturesFile, ModulesFile, OwnersFile, ReposFile};
use crate::model::routing::RoutingTestFile;
use crate::model::{HostBinding, ProfileConfig, Record, SkillConfig, UpstreamConfig};
use crate::util::{atomic_write, read_file_limited, safe_join};
use crate::versions::{PROTOCOL_ID, ReleaseManifest};

/// KB-root-relative directory holding the generated schemas.
pub const SCHEMAS_DIR: &str = "core/schemas";

/// File name suffix of generated schema files (other files, e.g. README.md, are ignored).
pub const SCHEMA_SUFFIX: &str = ".schema.json";

const DRAFT_2020_12: &str = "https://json-schema.org/draft/2020-12/schema";
const GENERATED_NOTE: &str =
    "Generated by `kb schema --write` from the Rust model in core/cli/src; do not edit.";
const MAX_SCHEMA_FILE_BYTES: u64 = 4 * 1024 * 1024;

/// Root schema of a model type, draft 2020-12.
fn model_schema<T: JsonSchema>() -> Value {
    SchemaSettings::draft2020_12()
        .into_generator()
        .into_root_schema_for::<T>()
        .to_value()
}

/// All generated schemas: file name → pretty JSON text with a trailing newline.
pub fn generate() -> BTreeMap<String, String> {
    let specs: [(&str, &str, &str, Value); 13] = [
        (
            "record",
            "Knowledge record front matter (document schema 1)",
            "TOML front matter of a record file, as JSON. One branch per `kind`.",
            model_schema::<Record>(),
        ),
        (
            "project",
            "Profile config (project/project.toml)",
            "Trusted profile configuration: namespace, approved source, knowledge roots.",
            model_schema::<ProfileConfig>(),
        ),
        (
            "registry-owners",
            "Owner registry (registry/owners.toml)",
            "Record owners and their authority (repos, product-wide).",
            model_schema::<OwnersFile>(),
        ),
        (
            "registry-repos",
            "Repository registry (registry/repos.toml)",
            "Host repositories described by the knowledge base.",
            model_schema::<ReposFile>(),
        ),
        (
            "registry-modules",
            "Module registry (registry/modules.toml)",
            "Modules of registry repos, with path globs and features.",
            model_schema::<ModulesFile>(),
        ),
        (
            "registry-features",
            "Feature registry (registry/features.toml)",
            "Product features, their repos and path globs.",
            model_schema::<FeaturesFile>(),
        ),
        (
            "registry-concepts",
            "Concept registry (registry/concepts.toml)",
            "Concepts with multilingual aliases and disambiguation path hints.",
            model_schema::<ConceptsFile>(),
        ),
        (
            "routing-test",
            "Routing fixtures (routing-tests/*.toml)",
            "Golden context requests with expected mandatory and forbidden ids.",
            model_schema::<RoutingTestFile>(),
        ),
        (
            "skill-config",
            "Skill settings (skill-config/skill.toml)",
            "Typed project settings for generated harness integrations.",
            model_schema::<SkillConfig>(),
        ),
        (
            "host-binding",
            "Host binding (.kbw.toml in a host repository)",
            "Optional host repo id, KB pin and snapshot selection.",
            model_schema::<HostBinding>(),
        ),
        (
            "upstream",
            "Upstream base (project/upstream.toml)",
            "Upstream revision the engine paths were last taken from.",
            model_schema::<UpstreamConfig>(),
        ),
        (
            "release-manifest",
            "Bootstrap and compatibility manifest (core/release.toml)",
            "Engine and contract versions, toolchain pin and path ownership.",
            model_schema::<ReleaseManifest>(),
        ),
        (
            "cli-envelope",
            "CLI machine output envelope (protocol kb.cli.v1)",
            "Document printed on stdout by every command in JSON mode.",
            envelope_schema(),
        ),
    ];
    specs
        .into_iter()
        .map(|(name, title, description, schema)| {
            let text = finish(schema, name, title, description);
            (format!("{name}.v1{SCHEMA_SUFFIX}"), text)
        })
        .collect()
}

/// Add identity and provenance keywords and render deterministically (sorted keys).
fn finish(schema: Value, name: &str, title: &str, description: &str) -> String {
    let mut root = match schema {
        Value::Object(m) => m,
        other => {
            let mut m = Map::new();
            m.insert("allOf".into(), json!([other]));
            m
        }
    };
    root.insert("$schema".into(), json!(DRAFT_2020_12));
    root.insert("$id".into(), json!(format!("kb:schema/{name}/v1")));
    root.insert("$comment".into(), json!(GENERATED_NOTE));
    root.insert("title".into(), json!(title));
    root.insert("description".into(), json!(description));
    let mut text = serde_json::to_string_pretty(&sorted(Value::Object(root)))
        .unwrap_or_else(|_| String::from("{}"));
    text.push('\n');
    text
}

/// Rebuild objects with keys in sorted order, independent of serde_json's map features.
fn sorted(v: Value) -> Value {
    match v {
        Value::Object(m) => {
            let entries: BTreeMap<String, Value> =
                m.into_iter().map(|(k, v)| (k, sorted(v))).collect();
            Value::Object(entries.into_iter().collect())
        }
        Value::Array(a) => Value::Array(a.into_iter().map(sorted).collect()),
        other => other,
    }
}

/// Hand-built schema of the `kb.cli.v1` envelope (docs/architecture.md §8).
fn envelope_schema() -> Value {
    let commands: Vec<String> = Cli::command()
        .get_subcommands()
        .map(|c| c.get_name().to_string())
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect();
    let codes: Vec<Value> = ErrorCode::ALL
        .iter()
        .map(|c| {
            json!({
                "properties": {
                    "code": {"const": c.as_str()},
                    "exit_code": {"const": c.exit_code()}
                }
            })
        })
        .collect();
    json!({
        "type": "object",
        "additionalProperties": false,
        "required": ["protocol", "command", "ok", "result", "error", "meta"],
        "properties": {
            "protocol": {"const": PROTOCOL_ID},
            "command": {
                "description": "The subcommand; null only when the arguments could not be parsed into a command.",
                "anyOf": [{"type": "string", "enum": commands}, {"type": "null"}]
            },
            "ok": {"type": "boolean"},
            "result": {"description": "Deterministic command result (command-specific); null on hard errors."},
            "error": {"anyOf": [{"type": "null"}, {"$ref": "#/$defs/Error"}]},
            "meta": {
                "type": "object",
                "description": "Non-deterministic metadata (timings); never part of the deterministic result."
            }
        },
        "if": {"properties": {"ok": {"const": true}}},
        "then": {"properties": {"error": {"type": "null"}}},
        "else": {"properties": {"error": {"$ref": "#/$defs/Error"}}},
        "$defs": {
            "Error": {
                "type": "object",
                "additionalProperties": false,
                "required": ["code", "exit_code", "message"],
                "properties": {
                    "code": {
                        "type": "string",
                        "enum": ErrorCode::ALL.iter().map(|c| c.as_str()).collect::<Vec<_>>()
                    },
                    "exit_code": {"type": "integer", "minimum": 1, "maximum": 255},
                    "message": {"type": "string"},
                    "details": {"description": "Structured, code-specific details."},
                    "hint": {"type": "string"},
                    "diagnostics": {"type": "array", "items": {"$ref": "#/$defs/Diagnostic"}}
                },
                "oneOf": codes
            },
            "Diagnostic": {
                "type": "object",
                "additionalProperties": false,
                "required": ["severity", "code", "message"],
                "properties": {
                    "severity": {"enum": ["error", "warning", "info"]},
                    "code": {"type": "string", "pattern": "^[A-Z][A-Z0-9_]*$"},
                    "path": {"type": "string"},
                    "record": {"type": "string"},
                    "line": {"type": "integer", "minimum": 0},
                    "message": {"type": "string"}
                }
            }
        }
    })
}

/// Existing `*.schema.json` files in `core/schemas` (name → bytes). Symlinks are refused.
fn existing(kb_root: &Path) -> Result<BTreeMap<String, Vec<u8>>> {
    let dir = safe_join(kb_root, SCHEMAS_DIR)?;
    let mut out = BTreeMap::new();
    let entries = match fs::read_dir(&dir) {
        Ok(e) => e,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(out),
        Err(e) => return Err(KbError::io(dir.display(), e)),
    };
    for entry in entries {
        let entry = entry.map_err(|e| KbError::io(dir.display(), e))?;
        let Some(name) = entry.file_name().to_str().map(str::to_string) else {
            continue;
        };
        if name.ends_with(SCHEMA_SUFFIX) {
            let bytes = read_file_limited(&entry.path(), MAX_SCHEMA_FILE_BYTES)?;
            out.insert(name, bytes);
        }
    }
    Ok(out)
}

/// Compare `core/schemas` with the generated schemas. Returns one entry per problem, as
/// `<kb-root-relative path>: missing|drifted|extra`, sorted by path.
pub fn check(kb_root: &Path) -> Result<Vec<String>> {
    let want = generate();
    let have = existing(kb_root)?;
    let mut problems = BTreeMap::new();
    for (name, text) in &want {
        match have.get(name) {
            None => {
                problems.insert(name.clone(), "missing");
            }
            Some(bytes) if bytes.as_slice() != text.as_bytes() => {
                problems.insert(name.clone(), "drifted");
            }
            Some(_) => {}
        }
    }
    for name in have.keys() {
        if !want.contains_key(name) {
            problems.insert(name.clone(), "extra");
        }
    }
    Ok(problems
        .into_iter()
        .map(|(name, status)| format!("{SCHEMAS_DIR}/{name}: {status}"))
        .collect())
}

/// Write the generated schemas into `core/schemas` (atomic per file) and remove stale
/// `*.schema.json` files. Returns the changes as `<path>: written|removed`; empty when
/// everything was already up to date.
pub fn write(kb_root: &Path) -> Result<Vec<String>> {
    let want = generate();
    let have = existing(kb_root)?;
    let mut changes = Vec::new();
    for (name, text) in &want {
        if have.get(name).map(Vec::as_slice) != Some(text.as_bytes()) {
            let path = safe_join(kb_root, &format!("{SCHEMAS_DIR}/{name}"))?;
            atomic_write(&path, text.as_bytes())?;
            changes.push(format!("{SCHEMAS_DIR}/{name}: written"));
        }
    }
    for name in have.keys().filter(|n| !want.contains_key(*n)) {
        let path = safe_join(kb_root, &format!("{SCHEMAS_DIR}/{name}"))?;
        fs::remove_file(&path).map_err(|e| KbError::io(path.display(), e))?;
        changes.push(format!("{SCHEMAS_DIR}/{name}: removed"));
    }
    changes.sort();
    Ok(changes)
}
